import type { Product, Carpenter, BlogPost } from './types';

export const categories = [
  { slug: 'sofa', name: 'Sofa' },
  { slug: 'beds', name: 'Beds' },
  { slug: 'dining', name: 'Dining' },
  { slug: 'tables', name: 'Tables' },
  { slug: 'chairs', name: 'Chairs' },
  { slug: 'wardrobes', name: 'Wardrobes' },
  { slug: 'premium', name: 'Premium' },
  { slug: 'budget', name: 'Budget' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Royal Oak Sofa',
    slug: 'royal-oak-sofa',
    category: 'Sofa',
    price: 49999,
    description: 'A luxurious sofa made from the finest royal oak, offering unparalleled comfort and style.',
    image: 'prod-1',
    dimensions: '220cm x 90cm x 85cm',
  },
  {
    id: '2',
    name: 'Modernist Bed',
    slug: 'modernist-bed',
    category: 'Beds',
    price: 35000,
    description: 'Sleek and minimalist bed frame, perfect for a contemporary bedroom aesthetic.',
    image: 'prod-2',
    dimensions: '180cm x 200cm x 90cm',
  },
  {
    id: '3',
    name: 'Grand Dining Table',
    slug: 'grand-dining-table',
    category: 'Dining',
    price: 65000,
    description: 'An expansive dining table that seats eight, crafted from rich mahogany.',
    image: 'prod-3',
    dimensions: '240cm x 100cm x 75cm',
  },
  {
    id: '4',
    name: 'Artisan Coffee Table',
    slug: 'artisan-coffee-table',
    category: 'Tables',
    price: 12500,
    description: 'A unique, handcrafted coffee table with intricate carvings.',
    image: 'prod-4',
    dimensions: '120cm x 60cm x 45cm',
  },
  {
    id: '5',
    name: 'Ergo-Comfort Chair',
    slug: 'ergo-comfort-chair',
    category: 'Chairs',
    price: 8999,
    description: 'Ergonomically designed chair for maximum comfort during long hours of sitting.',
    image: 'prod-5',
    dimensions: '60cm x 65cm x 110cm',
  },
  {
    id: '6',
    name: 'Heirloom Wardrobe',
    slug: 'heirloom-wardrobe',
    category: 'Wardrobes',
    price: 85000,
    description: 'A spacious and elegant wardrobe with classic design, built to last for generations.',
    image: 'prod-6',
    dimensions: '200cm x 60cm x 220cm',
  },
  {
    id: '7',
    name: 'Celestial Sofa (Premium)',
    slug: 'celestial-sofa-premium',
    category: 'Premium',
    price: 120000,
    description: 'The pinnacle of luxury. Upholstered in velvet with gold-plated accents.',
    image: 'prod-7',
    dimensions: '250cm x 100cm x 90cm',
  },
  {
    id: '8',
    name: 'Compact Study Table',
    slug: 'compact-study-table',
    category: 'Budget',
    price: 7500,
    description: 'A simple, sturdy, and affordable table for students and small spaces.',
    image: 'prod-8',
    dimensions: '100cm x 50cm x 75cm',
  },
  {
    id: '9',
    name: 'Plush Velvet Armchair',
    slug: 'plush-velvet-armchair',
    category: 'Chairs',
    price: 15999,
    description: 'Sink into the comfort of this plush velvet armchair, a perfect accent piece.',
    image: 'prod-9',
    dimensions: '85cm x 80cm x 95cm',
  },
  {
    id: '10',
    name: 'Rustic King Bed',
    slug: 'rustic-king-bed',
    category: 'Beds',
    price: 42000,
    description: 'A king-sized bed with a rustic finish, bringing warmth and character to your bedroom.',
    image: 'prod-10',
    dimensions: '190cm x 210cm x 120cm',
  },
];

export const carpenters: Carpenter[] = [
  {
    id: '1',
    name: 'Ramesh Kumar',
    experience: 15,
    rating: 4.8,
    hourlyRate: 500,
    specialty: ['Custom Furniture', 'Repairs', 'Polishing'],
    image: 'carpenter-1',
  },
  {
    id: '2',
    name: 'Suresh Singh',
    experience: 20,
    rating: 4.9,
    hourlyRate: 650,
    specialty: ['Antique Restoration', 'Intricate Carving'],
    image: 'carpenter-2',
  },
  {
    id: '3',
    name: 'Vikram Sharma',
    experience: 8,
    rating: 4.5,
    hourlyRate: 400,
    specialty: ['Modern Designs', 'Wardrobe Assembly'],
    image: 'carpenter-3',
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'The Ultimate Guide to Choosing the Right Wood',
    slug: 'guide-to-choosing-wood',
    excerpt: 'From oak to teak, we break down the pros and cons of different woods for your furniture.',
    author: 'Vishwakarma Experts',
    date: '2024-05-15',
    image: 'blog-1',
  },
  {
    id: '2',
    title: '5 Interior Design Trends to Watch in 2024',
    slug: 'interior-design-trends-2024',
    excerpt: 'Stay ahead of the curve with these stunning interior design trends that are making waves this year.',
    author: 'Design Weekly',
    date: '2024-05-10',
    image: 'blog-2',
  },
  {
    id: '3',
    title: 'How to Care for Your Luxury Furniture',
    slug: 'caring-for-luxury-furniture',
    excerpt: 'Keep your premium furniture looking its best with our essential maintenance tips.',
    author: 'The Craftsman',
    date: '2024-05-01',
    image: 'blog-3',
  },
];
